### PR TITLE
Initial import

### PR DESCRIPTION
**Pull request by andrewvc**
**Note: This is mostly complete but needs docs and perhaps a bit more testing!**

This is the initial import of code for a new filter `logstash-filter-script`. The aim of this plugin is to be a superior alternative to the `ruby` filter. Much of this design was discussed in https://github.com/elastic/logstash/issues/6847 . That design has been iterated on and revised to bring the features seen here.

The easiest way to understand these changes is to look at these sample files: https://github.com/andrewvc/logstash-filter-script/tree/initial-commit/spec/fixtures

## Improvements vs. Ruby Filter:

1. **File based script editing:** This allows for more complex logic than what is in a regular LS config
2. **Better debug-ability:** due to exceptions being tagged with the correct file:line information. Also, error logging should be improved here as well.
3. **Cleaner interface:** This plugin is also meant to serve as a testing ground for a new filter API for logstash
4. **Event generation:** The Ruby filter can only mutate existing events, this filter can mutate, drop, or add events.
5. **Flushing:** The ruby filter does not allow flushing, making it useless for many aggregations
6. **Testability:** The DSL used here has a simple test suite allowing users to test that their filter mutates events in expected ways

## TODO:
1. Add test methods for DLQ

### CODE REVIEW

**Comment by andrewvc** [comment]
@jsvd this is ready for an initial review. I'm going to hold off on better specs and docs until after that review.

I plan on writing very comprehensive docs for this plugin in a tutorial style. I think the docs will define the utility of this plugin.

**Comment by andrewvc** [comment]
@jsvd I'm thinking that there is so much in here right now, I'm not sure if we want to include batching in the initial PR.

I am wondering if the test suite could be improved to have expectations for objects sent to the DLQ.

**Comment by andrewvc** [comment]
WRT @colinsurprenant 's comment from the old thread

```
since the DSL filter and flush are callback style blocks, maybe we could rename them:

filter could become on_event
flush could become on_flush
and for batch support we could add on_batch
```

I'm a bit torn. On the one hand I'd like the script API to match the plugin API as closely as possible. On the other I'd like us to try new ideas here. A third approach, I hadn't considered until now, is not using blocks at all. Since I'm using `instance_eval` we could allow people to simply `def filter`.

I'm kind of leaning toward that at the moment. WDYT @colinsurprenant / @jsvd ?

**Comment by colinsurprenant** [comment]
@andrewvc or just support both the DSL `on_event {|event| ... }` **and** the method definition `def  on_event(event) { ... }`  
This is what I did in the Redstorm DSL, see https://github.com/colinsurprenant/redstorm/blob/cbb62efc529fd86b62f0fc39d8c8981256c2b55e/lib/red_storm/dsl/bolt.rb#L33-L43 

Basically the DSL actually creates an instance method, so if you go and just define that methods it will just work. Benchmarking showed that this was the best way to do it.

**Comment by colinsurprenant** [comment]
Now for my actual suggestion of using `on_event` instead of `filter`, basically its just a matter of having `on_event` conveying a better idea of what is happening, which is that your block will be called on each received event / that this is a callback. Same idea for `on_flush` and would also work for an eventual `on_batch`.  That way we dont't have to have a multi argument `filter` for both single event or batch, or have multiple filter like `filter` and `filter_batch` or what not.

It feels cleaner and more descriptive to me, but its a suggestion.

**Comment by andrewvc** [comment]
@colinsurprenant that makes sense. However, I'd rather only have one syntax personally. WDYT about *just* having the `def` version?

Thanks for the heads up about the perf improvement of `define_method` btw, that's good to know here.

**Comment by colinsurprenant** [comment]
@andrewvc personally I prefer the DSL + block syntax, I like that you don't have to define methods, you just hook in a code block to handle an event. Again this is my preference, but its mainly a style and syntax preference, I like the DSL feel. Both work.

**Comment by andrewvc** [comment]
@colinsurprenant well, one thing to consider in favor of the method syntax is that you can use `def` to define helper methods with this new version of the plugin. Using `def` makes that more discoverable.

Given that benefit, the performance benefit and the ease of implementation I'm in favor of starting with only the `def` interface for the initial release, and adding block syntax in a subsequent release if we find problems.

My issue with having multiple interfaces is that our target audience is not pro ruby programmers. I think consistency is more important than terseness for them, and moving to `def` would enable a more consistent experience.

**Comment by andrewvc** [comment]
@colinsurprenant I'm realizing that I didn't address your point about `on_event` etc. My original thought was that it would be good to have this API be as similar to the 'real' API as possible. But, the more I think through it, and the more variances I see, I think it's best to have it be as different as possible to reduce people's confusion. My proposal:

```ruby
api_version 1
concurrency :shared

def on_init
end

def on_event(event)
  [events...]
end

def on_flush(event)
  [events...]
end

# This is really the same as on final flush in a 'real' plugin
def on_close
  [events...]
end
```

WDYT?

**Comment by colinsurprenant** [comment]
@andrewvc I think the original intent of the Ruby filter was to provide a really easy way to inline a quick and small Ruby script and in that respect I think the DSL syntax has a bit less "Ruby" in your way, it feels more like you can just put your script block, while having to define a method feels more like a proper Ruby program. In other words, for me the DSL syntax it feels more "lightweight". But Frankly, its essentially aesthetic.

I am not sure I understand your helper methods comment? with the DSL syntax, nothing prevents the user from defining methods outside the DSL blocks? For exampe,
```ruby
def process_my_event(event)
  ...
  event
end

on_event { |event| process_my_event(event) }
```

So, for users writing more elaborate filters and with a better Ruby knowledge, they can totally structure their filter code and write classes and methods if they want to. 

Also, I don't think supporting both the block and methods "apis" would be that confusing. The way I see it is that we would provide example and doc mostly around the DSL syntax for the typical smaller use cases but also support the method definition if anyone with more Ruby experience feel better about defining methods instead of writing a block. 

Lastly, and that's a bit of an off topic comment, I think that on top of this awesome filter, another **really** important thing that will help our users write good scripts will be to provide a proper API doc for everything that can be done from this filter, for example the complete Event API, etc.

**Comment by andrewvc** [comment]
@colinsurprenant +1 on the docs comment. I fully agree that half the success here is a good guide people can use.

The more we discuss it the more I think these differences are not that major. Sometimes the most minor difference generate the longest discussions because the pros/cons are so fuzzy.

I move that we go forward with your approach re: `on_event` as callback style, and we also rewrite those to be method definitions for performance. WDYT?

**Comment by andrewvc** [comment]
Some other thoughts:

The test DSL uses the terms `test` and `expect` in weird ways. Additionally, I don't like the current approach I took to getting flush / close results as extra args in the `expect` block. I propose the syntax below.

```ruby
scenario "string repetition" do
  params { "foo" => "bar" }
  in_event { {"blah" => "baz" }

  assert_filter("blah gets repeated") do |events|
    events.first.get("blah") == "bazbaz"
  end

  assert_flush("nothing is flushed") do |events|
    events.empty?
  end

  assert_close("nothing is returned on close") do |events|
    events.empty?
  end  
```

**Comment by andrewvc** [comment]
Also, I move that I rename the `script_params` option to just `params` to bring it inline with the ES script processor. The only problem here is that the internal plugin API uses params as a reserved method! I think I can work around that, but we'll have to see.

**Comment by jordansissel** [comment]
I haven't had full time to digest this patch yet, but my main concerns are likely to be around naming (consistency and alignment).

At a quick glance:

* Having every method be prefixed with `on_` feels awkward. I know this was proposed and discussed, but it feels weird to have this in every method name.
* In the test, there is `params` -- is this the configuration of the plugin? Do we already have a word for a plugin's configuration in the public docs? (settings, config, something else?)

**Comment by andrewvc** [comment]
@jordansissel I'm open to changing params, and in fact, I think we need to. The current plugin API has a `params` accessor. This is confusing. I think we should change it to `config`.

WRT `on_` I actually don't have a strong opinion. I only care that we have a convention and stick to it.

**Comment by colinsurprenant** [comment]
I like `on_` handler names for callback style methods/blocks. I think it makes it very clear what the intention is on it, i.e. you write a `on_event` method or pass a block to the `on_event` DSL to be executed on every event. Simple, clear.

**Comment by andrewvc** [comment]
I think it's a problem to discuss clarity from a personal point of view for
a public API. The real question here is what our users will think.

I don't think we'll find a quantifiable answer on what's more clear, but I
can say I've seen both approaches out in the wild enough to say that no one
style dominates.

That being said, IMHO this has turned into bikeshedding. People will learn
it if we document it well and it isn't insane.

At this point I would like for there to be a clear distinction between what
the script filter does and the normal plugin API. I'd rather have there be
stark differences than subtle confusing ones.

**Comment by colinsurprenant** [comment]
@andrewvc agreed, mostly personal preference here. But it is definitely more interesting to discuss when there is a rationale behind this personal preference ;) It might feel like bikeshedding but at the same time naming can make a huge difference in API clarity, so I wouldn't dismiss it.

**Comment by andrewvc** [comment]
@colinsurprenant apologies if I seemed dismissive. I just want to make sure we don't get stuck on naming here :).

I think that all of the proposals I've seen so far are sensible. Given that, IMHO good documentation including a cookbook will deliver 90% of the ergonomic benefits here.

**Comment by andrewvc** [comment]
After meeting with @jsvd and @colinsurprenant we've decided to move the syntax / lifecycle to:

```
* def setup(options)
-- run --
* def on_event(event)
* def on_flush(false)
-- shutdown --
* def on_flush(true)
* def close
```

```
scenario "string repetition" do
  options { "foo" => "bar" }
  test_event { Event.new("blah" => "baz") }

  # All blocks evaled against plugin instance
  assert_setup("blah") do
    @file.opened?
  end

  assert_on_event("blah gets repeated") do |events|
    events.first.get("blah") == "bazbaz"
  end

  assert_on_flush("nothing is flushed") do |events|
    events.empty?
  end

  assert_on_final_flush("blah") do |events|
  end

  assert_close do
    @file.closed?
  end
end
```

**Comment by colinsurprenant** [comment]
quick note: I really like that idea we briefly discussed with @andrewvc and @jordansissel to maybe introduce a more generic timer event instead of a specific flushing callback. It could be something like "on_period" or "on_timer" or something around these lines, which could be used potentially for other purposes than just flushing, but flushing also if needed. 
Just need to iron out the idea of the final flush, a final timer event? not sure. Maybe just forget about that concept and simply keep *close*.

**Comment by andrewvc** [comment]
New goals from meeting today

* Remove disable tests option
* Add `on_event` option for inline
* Make options reachable from all callbacks

```
* def setup
-- run --
* def on_event(event)
-- shutdown --
* def close
```

```
scenario "string repetition" do
  options { "foo" => "bar" }
  test_events { [Event.new("blah" => "baz"), Event.new("bad" => "value")] }

  expected_events [
    Event.new("..."),
    Event.new("...")
  ]
end
```

**Comment by jsvd** [comment]
@andrewvc any thoughts of closing this now that we have logstash-plugins/logstash-filter-ruby#35 ?

**Comment by andrewvc** [comment]
I'm +1 on both closing this and deleting the repo

**Pull request closed without merging**
